name: discord-bot

version: "3.8"

services:
    # https://github.com/FlorianLeChat/Discord-BOT
    node:
        image: discord-bot
        restart: always
        deploy:
            resources:
                limits:
                    cpus: "1"
                    memory: 128M
                reservations:
                    cpus: "0.25"
                    memory: 32M
        build:
            context: .
            dockerfile: ./Dockerfile